package entidades;
// Generated 08-nov-2020 18:36:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Automovil generated by hbm2java
 */
@Entity
@Table(name="automovil"
    ,schema="public"
)
public class Automovil  implements java.io.Serializable {

    @Id
    @Column(name="automovilid", unique=true, nullable=false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
     private int automovilid;
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="modelo_id", nullable=false)
     private Modelo modelo;
    @Column(name="precio", precision=17, scale=17)
     private Double precio;
    @Column(name="color", length=30)
     private String color;
    @Column(name="aniofabricacion", nullable=false)
     private int aniofabricacion;
    @Column(name="stock", nullable=false)
     private int stock;
    @Column(name="km", nullable=false)
     private int km;
    @OneToMany(fetch=FetchType.LAZY, mappedBy="automovil")
     private Set<DetalleVenta> ventaDetalle = new HashSet<DetalleVenta>(0);
    public Automovil() {
    }

	
    public Automovil(int automovilid, Modelo modelo, int aniofabricacion) {
        this.automovilid = automovilid;
        this.modelo = modelo;
        this.aniofabricacion = aniofabricacion;
    }
    public Automovil(int automovilid, Modelo modelo, Double precio, String color, int aniofabricacion) {
       this.automovilid = automovilid;
       this.modelo = modelo;
       this.precio = precio;
       this.color = color;
       this.aniofabricacion = aniofabricacion;
    }

    public Automovil(Modelo modelo, Double precio, String color, int aniofabricacion) {
        this.modelo = modelo;
        this.precio = precio;
        this.color = color;
        this.aniofabricacion = aniofabricacion;
    }

    public Automovil(Modelo modelo, Double precio, String color, int aniofabricacion, int stock, int km) {
        this.modelo = modelo;
        this.precio = precio;
        this.color = color;
        this.aniofabricacion = aniofabricacion;
        this.stock = stock;
        this.km = km;
    }

    public Automovil(int automovilid, Modelo modelo, Double precio, String color, int aniofabricacion, int stock, int km) {
        this.automovilid = automovilid;
        this.modelo = modelo;
        this.precio = precio;
        this.color = color;
        this.aniofabricacion = aniofabricacion;
        this.stock = stock;
        this.km = km;
    }

    public Set<DetalleVenta> getVentaDetalle() {
        return ventaDetalle;
    }

    public void setVentaDetalle(Set<DetalleVenta> ventaDetalle) {
        this.ventaDetalle = ventaDetalle;
    }

    public int getStock() {
        return stock;
    }

    public void setStock(int stock) {
        this.stock = stock;
    }

    public int getKm() {
        return km;
    }

    public void setKm(int km) {
        this.km = km;
    }
  
    public int getAutomovilid() {
        return this.automovilid;
    }
    
    public void setAutomovilid(int automovilid) {
        this.automovilid = automovilid;
    }


    public Modelo getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }

    
    
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }

    
    
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }

    
    
    public int getAniofabricacion() {
        return this.aniofabricacion;
    }
    
    public void setAniofabricacion(int aniofabricacion) {
        this.aniofabricacion = aniofabricacion;
    }

}


