package entidades;
// Generated 08-nov-2020 18:36:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Automovil generated by hbm2java
 */
@Entity
@Table(name="automovil"
    ,schema="public"
)
public class Automovil  implements java.io.Serializable {

    @Id
    @Column(name="automovilid", unique=true, nullable=false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
     private Long automovilid;
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="marcaid", nullable=false)
     private Marca marca;
    @Column(name="precioreferencia", precision=17, scale=17)
     private Double precioreferencia;
    @Column(name="color", length=30)
     private String color;
    @Column(name="aniofabricacion", nullable=false)
     private int aniofabricacion;
    @Column(name="modelomarca", length=30)
     private String modelomarca;
    @OneToMany(fetch=FetchType.LAZY, mappedBy="automovil")
     private Set<Auto> autos = new HashSet<Auto>(0);

    public Automovil() {
    }

	
    public Automovil(Long automovilid, Marca marca, int aniofabricacion) {
        this.automovilid = automovilid;
        this.marca = marca;
        this.aniofabricacion = aniofabricacion;
    }
    public Automovil(Long automovilid, Marca marca, Double precioreferencia, String color, int aniofabricacion, Set<Auto> autos) {
       this.automovilid = automovilid;
       this.marca = marca;
       this.precioreferencia = precioreferencia;
       this.color = color;
       this.aniofabricacion = aniofabricacion;
       this.autos = autos;
    }

    public Automovil(Marca marca, Double precioreferencia, String color, int aniofabricacion, String modelomarca) {
        this.marca = marca;
        this.precioreferencia = precioreferencia;
        this.color = color;
        this.aniofabricacion = aniofabricacion;
        this.modelomarca = modelomarca;
    }

    

    public String getModelomarca() {
        return modelomarca;
    }

    public void setModelomarca(String modelomarca) {
        this.modelomarca = modelomarca;
    }
   
     
    public Long getAutomovilid() {
        return this.automovilid;
    }
    
    public void setAutomovilid(Long automovilid) {
        this.automovilid = automovilid;
    }


    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }

    
    
    public Double getPrecioreferencia() {
        return this.precioreferencia;
    }
    
    public void setPrecioreferencia(Double precioreferencia) {
        this.precioreferencia = precioreferencia;
    }

    
    
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }

    
    
    public int getAniofabricacion() {
        return this.aniofabricacion;
    }
    
    public void setAniofabricacion(int aniofabricacion) {
        this.aniofabricacion = aniofabricacion;
    }


    public Set<Auto> getAutos() {
        return this.autos;
    }
    
    public void setAutos(Set<Auto> autos) {
        this.autos = autos;
    }

    @Override
    public String toString() {
        return marca + " , " + modelomarca + ", " + aniofabricacion + ", " + color;
    }




}


