package entidades;
// Generated 08-nov-2020 18:36:10 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,schema="public"
)
public class Cliente  implements java.io.Serializable {

    @Id
    @Column(name = "clienteid", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int clienteid;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "persona_id", nullable = false)
    private Persona persona;
    @Temporal(TemporalType.DATE)
    @Column(name = "fechaalta", nullable = false, length = 30)
    private Date fechaalta;
    @Column(name = "email", nullable = false, length = 30)
    private String email;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
    private Set<Venta> ventas = new HashSet<Venta>(0);

    public Cliente() {
    }

	
    public Cliente(int clienteid, Persona persona, Date fechaalta, String email) {
        this.clienteid = clienteid;
        this.persona = persona;
        this.fechaalta = fechaalta;
        this.email = email;
    }
    public Cliente(int clienteid, Persona persona, Date fechaalta, String email, Set<Venta> ventas) {
       this.clienteid = clienteid;
       this.persona = persona;
       this.fechaalta = fechaalta;
       this.email = email;
       this.ventas = ventas;
    }

    public Cliente(Date fechaalta, String email) {
        this.fechaalta = fechaalta;
        this.email = email;
    }

    public Cliente(Persona persona, Date fechaalta, String email) {
        this.persona = persona;
        this.fechaalta = fechaalta;
        this.email = email;
    }

    public int getClienteid() {
        return this.clienteid;
    }
    
    public void setClienteid(int clienteid) {
        this.clienteid = clienteid;
    }

    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
//    @Column(name="fechaalta", nullable=false, length=13)
    public Date getFechaalta() {
        return this.fechaalta;
    }
    
    public void setFechaalta(Date fechaalta) {
        this.fechaalta = fechaalta;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }

    @Override
    public String toString() {
        return persona.getNombre() + " " + persona.getApellido();
    }
}


