package entidades;
// Generated 08-nov-2020 18:36:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Marca generated by hbm2java
 */
@Entity
@Table(name="marca"
    ,schema="public"
)
public class Marca  implements java.io.Serializable {

     @Column(name="marcaid", unique=true, nullable=false)
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     private Long marcaid;
     @Column(name="nombre", nullable=false, length=60)
     private String nombre;
     @Column(name="paisdeorigen", length=60)
     private String paisdeorigen;
     @OneToMany(fetch=FetchType.LAZY, mappedBy="marca")
     private Set<Automovil> automoviles = new HashSet<Automovil>(0);

    public Marca() {
    }

    public Marca(String nombre, String paisdeorigen) {
        this.nombre = nombre;
        this.paisdeorigen = paisdeorigen;
    }

	
    public Marca(long marcaid, String nombre) {
        this.marcaid = marcaid;
        this.nombre = nombre;
    }
    public Marca(long marcaid, String nombre, String paisdeorigen, Set<Automovil> automovils) {
       this.marcaid = marcaid;
       this.nombre = nombre;
       this.paisdeorigen = paisdeorigen;
       this.automoviles = automovils;
    }

    public Marca(Long marcaid, String nombre, String paisdeorigen) {
        this.marcaid = marcaid;
        this.nombre = nombre;
        this.paisdeorigen = paisdeorigen;
    }

    
    public Long getMarcaid() {
        return (long) this.marcaid;
    }
    
    public void setMarcaid(long marcaid) {
        this.marcaid = marcaid;
    }

    
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    public String getPaisdeorigen() {
        return this.paisdeorigen;
    }
    
    public void setPaisdeorigen(String paisdeorigen) {
        this.paisdeorigen = paisdeorigen;
    }

    public Set<Automovil> getAutomovils() {
        return this.automoviles;
    }
    
    public void setAutomovils(Set<Automovil> automovils) {
        this.automoviles = automovils;
    }

    @Override
    public String toString() {
        return  nombre;
    }

    
   

   




}


