package entidades;
// Generated 08-nov-2020 18:36:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Modelo generated by hbm2java
 */
@Entity
@Table(name="modelo"
    ,schema="public"
)
public class Modelo  implements java.io.Serializable {

     @Column(name="modeloid", unique=true, nullable=false)
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     private long modeloid;
     @Column(name="marca", nullable=false, length=60)
     private String marca;
     @Column(name="nombre", length=60)
     private String nombre;
     @OneToMany(fetch=FetchType.LAZY, mappedBy="modelo")
     private Set<Automovil> automoviles = new HashSet<Automovil>(0);

    public Modelo() {
    }

    public Modelo(String marca, String nombre) {
        this.marca = marca;
        this.nombre = nombre;
    }

	
    public Modelo(long modeloid, String marca) {
        this.modeloid = modeloid;
        this.marca = marca;
    }
    public Modelo(long modeloid, String marca, String nombre, Set<Automovil> automovils) {
       this.modeloid = modeloid;
       this.marca = marca;
       this.nombre = nombre;
       this.automoviles = automovils;
    }

    public Modelo(long modeloid, String marca, String nombre) {
        this.modeloid = modeloid;
        this.marca = marca;
        this.nombre = nombre;
    }

    
    public long getModeloid() {
        return this.modeloid;
    }
    
    public void setModeloid(long modeloid) {
        this.modeloid = modeloid;
    }

    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Set<Automovil> getAutomovils() {
        return this.automoviles;
    }
    
    public void setAutomovils(Set<Automovil> automovils) {
        this.automoviles = automovils;
    }

    @Override
    public String toString() {
        return marca + "," + nombre;
    }

    
}


