package entidades;
// Generated 08-nov-2020 18:36:10 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pago generated by hbm2java
 */
@Entity
@Table(name="pago"
    ,schema="public"
)
public class Pago  implements java.io.Serializable {
   

    @Id
    @Column(name="pagoid", unique=true, nullable=false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
     private Long pagoid;
@ManyToOne(fetch=FetchType.LAZY)
     @JoinColumn(name="venta_id", nullable=false)
     private Venta venta;
@Temporal(TemporalType.DATE)
     @Column(name="fechapago", nullable=false, length=13)
     private Date fechapago;
@Temporal(TemporalType.DATE)
     @Column(name="fechavencimiento", nullable=false, length=13)
     private Date fechavencimiento;
@Column(name="monto", nullable=false, precision=17, scale=17)
     private double monto;
@Column(name="forma", nullable=false, length=60)
     private String forma;

    public Pago() {
    }

    public Pago(long pagoid, Venta venta, Date fechapago, Date fechavencimiento, double monto, String forma) {
       this.pagoid = pagoid;
       this.venta = venta;
       this.fechapago = fechapago;
       this.fechavencimiento = fechavencimiento;
       this.monto = monto;
       this.forma = forma;
    }
   
    public long getPagoid() {
        return this.pagoid;
    }
    
    public void setPagoid(long pagoid) {
        this.pagoid = pagoid;
    }

    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }

    public Date getFechapago() {
        return this.fechapago;
    }
    
    public void setFechapago(Date fechapago) {
        this.fechapago = fechapago;
    }

    public Date getFechavencimiento() {
        return this.fechavencimiento;
    }
    
    public void setFechavencimiento(Date fechavencimiento) {
        this.fechavencimiento = fechavencimiento;
    }

    
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }

    
    public String getForma() {
        return this.forma;
    }
    
    public void setForma(String forma) {
        this.forma = forma;
    }




}


