package entidades;
// Generated 08-nov-2020 18:36:10 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="persona"
    ,schema="public"
)
public class Persona  implements java.io.Serializable {

     @Id
     @Column(name="personaid", unique=true, nullable=false)
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     private int personaid;
     @Column(name="nombre", nullable=false, length=60)
     private String nombre;
     @Column(name="apellido", nullable=false, length=60)
     private String apellido;
     @Column(name="dni", nullable=false, length=30)
     private String dni;
     @Temporal(TemporalType.DATE)
     @Column(name="fechanacimiento", nullable=false, length=13)
     private Date fechanacimiento;
     @Column(name="telefono", length=30)
     private String telefono;
     @Column(name="direccion", length=80)
     private String direccion;
     @Column(name="ciudad", length=80)
     private String ciudad;
     @Column(name="codpostal", length=30)
     private String codpostal;
     @OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
     private Set<Vendedor> vendedors = new HashSet<Vendedor>(0);
     @OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     @OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
     private Set<Cliente> clientes = new HashSet<Cliente>(0);

    public Persona() {
    }

	
    public Persona(int personaid, String nombre, String apellido, String dni, Date fechanacimiento) {
        this.personaid = personaid;
        this.nombre = nombre;
        this.apellido = apellido;
        this.dni = dni;
        this.fechanacimiento = fechanacimiento;
    }
    public Persona(int personaid, String nombre, String apellido, String dni, Date fechanacimiento, String telefono, String direccion, String ciudad, String codpostal, Set<Vendedor> vendedors, Set<Usuario> usuarios, Set<Cliente> clientes) {
       this.personaid = personaid;
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.fechanacimiento = fechanacimiento;
       this.telefono = telefono;
       this.direccion = direccion;
       this.ciudad = ciudad;
       this.codpostal = codpostal;
       this.vendedors = vendedors;
       this.usuarios = usuarios;
       this.clientes = clientes;
    }

    public Persona(Date fechanacimiento, String nombre, String apellido, 
            String dni, String telefono, String direccion, String ciudad, String codpostal) {
        
        this.fechanacimiento = fechanacimiento;
        this.nombre = nombre;
        this.apellido = apellido;
        this.dni = dni;
        this.telefono = telefono;
        this.direccion = direccion;
        this.ciudad = ciudad;
        this.codpostal = codpostal;
    }

  
   
   
    public int getPersonaid() {
        return this.personaid;
    }
    
    public void setPersonaid(int personaid) {
        this.personaid = personaid;
    }

    
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }

    
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    
    public String getCodpostal() {
        return this.codpostal;
    }
    
    public void setCodpostal(String codpostal) {
        this.codpostal = codpostal;
    }

    public Set<Vendedor> getVendedors() {
        return this.vendedors;
    }
    
    public void setVendedors(Set<Vendedor> vendedors) {
        this.vendedors = vendedors;
    }

    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }




}


