package entidades;
// Generated 08-nov-2020 18:36:10 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
)
public class Usuario  implements java.io.Serializable {


     @Column(name="usuarioid", unique=true, nullable=false)
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     private Long usuarioid;
     @ManyToOne(fetch=FetchType.LAZY)
     @JoinColumn(name="personaid", nullable=false)
     private Persona persona;
     @Column(name="username", nullable=false, length=60)
     private String username;
     @Column(name="password", nullable=false, length=60)
     private String password;

    public Usuario() {
    }

    public Usuario(Long usuarioid, Persona persona, String username, String password) {
       this.usuarioid = usuarioid;
       this.persona = persona;
       this.username = username;
       this.password = password;
    }
   
    public long getUsuarioid() {
        return (long) this.usuarioid;
    }
    
    public void setUsuarioid(long usuarioid) {
        this.usuarioid = usuarioid;
    }

    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


