package entidades;
// Generated 08-nov-2020 18:36:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vendedor generated by hbm2java
 */
@Entity
@Table(name="vendedor"
    ,schema="public"
)
public class Vendedor  implements java.io.Serializable {

     @Id
     @Column(name="vendedorid", unique=true, nullable=false)
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     private long vendedorid;
     @ManyToOne(fetch=FetchType.LAZY)
     @JoinColumn(name="personaid", nullable=false)
     private Persona persona;
     @Column(name="legajo", nullable=false, length=30)
     private String legajo;
     @Column(name="telefono_ventas", length=30)
     private String telefonoVentas;
     @Column(name="email_ventas", length=30)
     private String emailVentas;
     @OneToMany(fetch=FetchType.LAZY, mappedBy="vendedor")
     private Set<Venta> ventas = new HashSet<Venta>(0);

    public Vendedor() {
    }

	
    public Vendedor(long vendedorid, Persona persona, String legajo) {
        this.vendedorid = vendedorid;
        this.persona = persona;
        this.legajo = legajo;
    }
    public Vendedor(int vendedorid, Persona persona, String legajo, String telefonoVentas, String emailVentas, Set<Venta> ventas) {
       this.vendedorid = vendedorid;
       this.persona = persona;
       this.legajo = legajo;
       this.telefonoVentas = telefonoVentas;
       this.emailVentas = emailVentas;
       this.ventas = ventas;
    }

    public Vendedor(Persona persona, String legajo, String telefonoVentas, String emailVentas) {
        this.persona = persona;
        this.legajo = legajo;
        this.telefonoVentas = telefonoVentas;
        this.emailVentas = emailVentas;
    }
    
    
   
    public long getVendedorid() {
        return this.vendedorid;
    }
    
    public void setVendedorid(long vendedorid) {
        this.vendedorid = vendedorid;
    }

    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
    public String getLegajo() {
        return this.legajo;
    }
    
    public void setLegajo(String legajo) {
        this.legajo = legajo;
    }

    
    public String getTelefonoVentas() {
        return this.telefonoVentas;
    }
    
    public void setTelefonoVentas(String telefonoVentas) {
        this.telefonoVentas = telefonoVentas;
    }

    
    public String getEmailVentas() {
        return this.emailVentas;
    }
    
    public void setEmailVentas(String emailVentas) {
        this.emailVentas = emailVentas;
    }

    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }




}


