package entidades;
// Generated 08-nov-2020 18:36:10 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venta generated by hbm2java
 */
@Entity
@Table(name="venta"
    ,schema="public"
)
public class Venta  implements java.io.Serializable {

    @Id
    @Column(name="ventaid", unique=true, nullable=false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
     private long ventaid;
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente_id", nullable=false)
     private Cliente cliente;
@ManyToOne(fetch=FetchType.LAZY)
     @JoinColumn(name="vendedor_id", nullable=false)
     private Vendedor vendedor;
@Temporal(TemporalType.DATE)
     @Column(name="fechaventa", nullable=false, length=13)
     private Date fechaventa;
@Column(name="montototal", precision=17, scale=17)
     private Double montototal;
@Column(name="cantcuotas", nullable=false)
     private int cantcuotas;
@Column(name="estado", length=30)
     private String estado;
@OneToMany(fetch=FetchType.LAZY, mappedBy="venta")
     private Set<Pago> pagos = new HashSet<Pago>(0);

    public Venta() {
    }

	
    public Venta(long ventaid, Cliente cliente, Vendedor vendedor, Date fechaventa, int cantcuotas) {
        this.ventaid = ventaid;
        this.cliente = cliente;
        this.vendedor = vendedor;
        this.fechaventa = fechaventa;
        this.cantcuotas = cantcuotas;
    }
    public Venta(int ventaid, Cliente cliente, Vendedor vendedor, Date fechaventa, Double montototal, int cantcuotas, String estado, Set<Pago> pagos) {
       this.ventaid = ventaid;
       this.cliente = cliente;
       this.vendedor = vendedor;
       this.fechaventa = fechaventa;
       this.montototal = montototal;
       this.cantcuotas = cantcuotas;
       this.estado = estado;
       this.pagos = pagos;
    }
   
    public long getVentaid() {
        return this.ventaid;
    }
    
    public void setVentaid(long ventaid) {
        this.ventaid = ventaid;
    }

    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }

    public Date getFechaventa() {
        return this.fechaventa;
    }
    
    public void setFechaventa(Date fechaventa) {
        this.fechaventa = fechaventa;
    }

    
    public Double getMontototal() {
        return this.montototal;
    }
    
    public void setMontototal(Double montototal) {
        this.montototal = montototal;
    }

    
    public int getCantcuotas() {
        return this.cantcuotas;
    }
    
    public void setCantcuotas(int cantcuotas) {
        this.cantcuotas = cantcuotas;
    }

    
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Set<Pago> getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set<Pago> pagos) {
        this.pagos = pagos;
    }




}


